# Generated by Django 3.0.7 on 2021-07-21 10:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('six_months_price', models.CharField(max_length=20)),
                ('six_months_description', models.CharField(max_length=250)),
                ('year_price', models.CharField(max_length=20)),
                ('year_description', models.CharField(max_length=250)),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_confirmation', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST', null=True)),
                ('expire_date', models.DateTimeField(blank=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST', null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Plans')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=100)),
                ('markdown_content', models.TextField(blank=True, max_length=20000, validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('conent_type', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST')),
                ('publish', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
