# Generated by Django 3.0.7 on 2021-07-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plans',
            options={'ordering': ['level'], 'verbose_name_plural': 'plans'},
        ),
        migrations.AddField(
            model_name='plans',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
