# Generated by Django 3.0.7 on 2022-05-01 10:21

import django.core.validators
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20210721_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='rgb',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='plans',
            name='created_date',
            field=models.DateTimeField(auto_now=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST'),
        ),
        migrations.AddField(
            model_name='plans',
            name='long_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plans',
            name='markdown_content',
            field=models.TextField(blank=True, max_length=20000, validators=[django.core.validators.MaxLengthValidator(20000)]),
        ),
        migrations.AddField(
            model_name='plans',
            name='price_description',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plans',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='description',
            field=models.TextField(blank=True, max_length=20000, validators=[django.core.validators.MaxLengthValidator(20000)]),
        ),

    ]
