# Generated by Django 3.0.7 on 2022-05-16 21:12

from django.db import migrations, models
import django.core.validators
import django_mysql.models

class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20220501_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='long_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='schedule',
            field=models.TextField(blank=True, max_length=20000, validators=[django.core.validators.MaxLengthValidator(20000)]),
        ),
    ]
