apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: {{ include "academy.fullname" . }}
  name: {{ include "academy.name" . }}-redis-endpoint
spec:
  ports:
    - name: http
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app.kubernetes.io/name: {{ include "academy.name" . }}-redis
    app: {{ include "academy.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}-redis
