# Generated by Django 3.0.7 on 2023-12-11 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubactivitys',
            name='activity_description',
            field=models.TextField(blank=True, max_length=100, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
