# Generated by Django 3.0.7 on 2023-12-06 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubactivitys',
            old_name='event_id',
            new_name='commit_id',
        ),
        migrations.RenameField(
            model_name='githubactivitys',
            old_name='event_type',
            new_name='distinct',
        ),
        migrations.RenameField(
            model_name='githubactivitys',
            old_name='repo_name',
            new_name='tree_id',
        ),
        migrations.RenameField(
            model_name='githubactivitys',
            old_name='user_name',
            new_name='url',
        ),
        migrations.AddField(
            model_name='githubactivitys',
            name='added',
            field=models.TextField(blank=True, max_length=1750, validators=[django.core.validators.MaxLengthValidator(1750)]),
        ),
        migrations.AddField(
            model_name='githubactivitys',
            name='author',
            field=models.TextField(blank=True, max_length=1750, validators=[django.core.validators.MaxLengthValidator(1750)]),
        ),
        migrations.AddField(
            model_name='githubactivitys',
            name='committer',
            field=models.TextField(blank=True, max_length=1750, validators=[django.core.validators.MaxLengthValidator(1750)]),
        ),
        migrations.AddField(
            model_name='githubactivitys',
            name='message',
            field=models.TextField(blank=True, max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AddField(
            model_name='githubactivitys',
            name='modified',
            field=models.TextField(blank=True, max_length=1750, validators=[django.core.validators.MaxLengthValidator(1750)]),
        ),
        migrations.AddField(
            model_name='githubactivitys',
            name='removed',
            field=models.TextField(blank=True, max_length=1750, validators=[django.core.validators.MaxLengthValidator(1750)]),
        ),
    ]
