# Generated by Django 3.0.7 on 2023-12-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubactivitys',
            name='activity_description',
            field=models.CharField(max_length=10),
        ),
    ]
