# Generated by Django 3.0.7 on 2023-12-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231212_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubactivitys',
            name='event_link',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
