# Generated by Django 3.0.7 on 2023-12-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231206_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubactivitys',
            old_name='event_id',
            new_name='event_type',
        ),
    ]
