# Generated by Django 3.0.7 on 2023-12-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20231206_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubactivitys',
            name='created_at',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
