# Generated by Django 3.0.7 on 2023-12-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_githubactivitys_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubactivitys',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST', null=True),
        ),
    ]
